steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sep6-group2/sep6:$SHORT_SHA', 'api']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sep6-group2/sep6:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'sep6', '--region=europe-west1', '--platform=managed', '--image=gcr.io/sep6-group2/sep6:$SHORT_SHA']

