steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sep6-group2/sep6-backend:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sep6-group2/sep6-backend:$SHORT_SHA']  
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'sep6-backend', '--region=europe-west1', '--platform=managed', '--image=gcr.io/sep6-group2/sep6-backend:$SHORT_SHA'] 

