version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=sep6
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=united_airplanes_db
    volumes:
      - database:/var/lib/mysql
      - ./db/dump:/docker-entrypoint-initdb.d
    networks:
      - sep6_airplanes_network

  api-server:
    build: ./api
    ports:
      - "3257:3257"
    environment:
      - DATABASE_URL=mysql://sep6:123456@mysql:3306/united_airplanes_db
    depends_on:
      - mysql
    networks:
      - sep6_airplanes_network
    volumes:
      - ./api:/usr/src/app

volumes:
  database:

networks:
  sep6_airplanes_network:
    driver: bridge


